version: 2
jobs:
  build_toolbox:
    working_directory: /rackspace-toolbox
    docker:
      - image: docker:18.06.1-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip
      - deploy:
          name: Build rackspace-toolbox containers
          command: |
            docker build -t rackspace-toolbox:$CIRCLE_SHA1 -f toolbox/Dockerfile .

            docker login -u $DOCKER_USER -p $DOCKER_PASS

            docker tag rackspace-toolbox:$CIRCLE_SHA1 "rackautomation/rackspace-toolbox:$CIRCLE_SHA1"
            docker push "rackautomation/rackspace-toolbox:$CIRCLE_SHA1"

  test_toolbox:
    docker:
      - image: rackautomation/rackspace-toolbox:$CIRCLE_SHA1
    steps:
      - checkout
      - run:
          name: check old
          command: cd test && check_old.sh
      - run:
          name: lint tests
          command: cd test && lint.sh
      - run:
          name: plan
          command: cd test && plan.sh
      - run:
          name: apply
          command: cd test && apply.sh || echo "apply failed."
      - run:
          name: destroy
          command: cd test && destroy.sh

  test:
    docker:
      - image: hashicorp/terraform:0.11.8
    steps:
      - checkout
      - run: mv repository_template/bin test/bin
      - run:
          name: lint tests
          command: cd test && ./bin/lint.sh
      - run:
          name: plan
          command: cd test && ./bin/plan.sh
      - run:
          name: apply
          command: cd test && ./bin/apply.sh || echo "apply failed."
      - run:
          name: destroy
          command: cd test && ./bin/destroy.sh  # must succeed or we have something to clean up manually

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_toolbox
      - test_toolbox:
         requires:
           - build_toolbox
      - test:
          filters:
            branches:
             ignore: master
