version: 2
jobs:
  test:
    docker:
      - image: hashicorp/terraform:0.11.7
    steps:
      - checkout
      - run: mv repository_templates/bin bin
      - run: mkdir layers && mv aviator/* layers/
      - run:
          name: lint
          command: bin/lint.sh
      - run:
          name: validate
          command: bin/validate.sh

      # future testing of actual templates

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
