version: 2
jobs:
  build_toolbox:
    working_directory: /rackspace-toolbox
    docker:
      - image: docker:18.06.1-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip
      - deploy:
          name: Build rackspace-toolbox containers
          command: |
            docker build -t rackspace-toolbox:$CIRCLE_SHA1 -f toolbox/Dockerfile .

            docker login -u $DOCKER_USER -p $DOCKER_PASS

            docker tag rackspace-toolbox:$CIRCLE_SHA1 "rackautomation/rackspace-toolbox:$CIRCLE_SHA1"
            docker push "rackautomation/rackspace-toolbox:$CIRCLE_SHA1"

  test_toolbox:
    docker:
      - image: rackautomation/rackspace-toolbox:$CIRCLE_SHA1
    environment:
      TF_STATE_BUCKET: test_harness # these don't have any effect since we don't
      TF_STATE_REGION: test_harness # have any actual layers defined in the repo
    steps:
      - checkout
      - run:
          name: check old
          command: cd test && check_old.sh
      - run:
          name: lint tests
          command: cd test && lint.sh
      - run:
          name: plan
          command: cd test && plan.sh
      - run:
          name: apply
          command: cd test && apply.sh || echo "apply failed."
      - run:
          name: destroy
          command: cd test && destroy.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_toolbox
      - test_toolbox:
         requires:
           - build_toolbox
