version: 2
jobs:
  test:
    docker:
      - image: hashicorp/terraform:0.11.8
    steps:
      - checkout
      - run: mv repository_template/bin test/bin
      - run:
          name: lint tests
          command: cd test && ./bin/lint.sh
      - run:
          name: plan
          command: cd test && ./bin/plan.sh
      - run:
          name: apply
          command: cd test && ./bin/apply.sh || echo "apply failed."
      - run:
          name: destroy
          command: cd test && ./bin/destroy.sh  # must succeed or we have something to clean up manually

workflows:
  version: 2
  build_and_test:
    jobs:
      - test:
          filters:
            branches:
             ignore: master
