version: 2
jobs:
  test:
    docker:
      - image: hashicorp/terraform:0.11.7
    steps:
      - checkout
      - run: mv repository_templates/scripts scripts
      - run: mkdir layers && mv aviator layers/
      - run:
          name: lint
          command: ./scripts/lint.sh
      - run:
          name: validate
          command: ./scripts/validate.sh

      # future testing of actual templates

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
