version: 2.1
jobs:
  build_toolbox:
    executor: gcp-gcr/default
    steps:
      - checkout
      - gcp-gcr/gcr-auth
      - deploy:
          name: Build rackspace-toolbox containers
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t rackautomation/rackspace-toolbox:$CIRCLE_SHA1 ./toolbox/
            docker push rackautomation/rackspace-toolbox:$CIRCLE_SHA1
            ./scripts/tag_release $CIRCLE_SHA1 "branch_${CIRCLE_BRANCH}"

  test_toolbox:
    docker:
      - image: rackautomation/rackspace-toolbox:$CIRCLE_SHA1
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - checkout
      - run:
          name: run tests
          command: |
            git clone --depth 1 https://github.com/bats-core/bats-core.git /tmp/bats
            /tmp/bats/install.sh /usr/local
            time bats -f '^[^@]' ./tests
      - add_ssh_keys
      - run:
          name: smoke tests pulling credentials and using state file on S3
          command: |
            unset AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN
            export KEY_FILE=$(ssh -G git@github.com | grep identityfile | cut -d' ' -f2 | head -n1)
            time bats -f '@smoke' ./tests

  tag_master:
    executor: gcp-gcr/default
    steps:
      - checkout
      - gcp-gcr/gcr-auth
      - deploy:
          name: tag as master
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            ./scripts/tag_release $CIRCLE_SHA1 master

  tag_release:
    executor: gcp-gcr/default
    steps:
      - checkout
      - gcp-gcr/gcr-auth
      - deploy:
          name: tag an official release
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            ./scripts/tag_release $CIRCLE_SHA1 $CIRCLE_TAG

orbs:
  gcp-gcr: circleci/gcp-gcr@0.9.0

workflows:
  version: 2
  toolbox:
    jobs:
      - build_toolbox
      - test_toolbox:
          requires:
            - build_toolbox
      - tag_master:
          requires:
            - test_toolbox
          filters:
            branches:
              only:
                - master
      - tag_release:
          filters:
            tags:
              only:
                - /^[0-9]\.[0-9]\.[0-9]+/
            branches:
              ignore: /.*/
