version: 2
jobs:
  build:
    environment:
      AWS_DEFAULT_REGION: us-west-2
      ECR_ENDPOINT: 042423532529.dkr.ecr.us-west-2.amazonaws.com
    working_directory: /rackspace-toolbox
    docker:
      - image: docker:18.06.1-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip
            pip install awscli
      - deploy:
          name: Build rackspace-toolbox
          command: |
            docker build -t rackspace-toolbox -f toolbox/Dockerfile .
            $(aws ecr get-login --registry-ids 042423532529 --no-include-email)
            docker tag rackspace-toolbox "$ECR_ENDPOINT/rackspace-toolbox:$CIRCLE_SHA1"
            docker push "$ECR_ENDPOINT/rackspace-toolbox:$CIRCLE_SHA1"
  test:
    docker:
      - image: hashicorp/terraform:0.11.8
    steps:
      - checkout
      - run: mv repository_template/bin test/bin
      - run:
          name: lint tests
          command: cd test && ./bin/lint.sh
      - run:
          name: plan
          command: cd test && ./bin/plan.sh
      - run:
          name: apply
          command: cd test && ./bin/apply.sh || echo "apply failed."
      - run:
          name: destroy
          command: cd test && ./bin/destroy.sh  # must succeed or we have something to clean up manually

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          filters:
            branches:
             ignore: master
