version: 2
jobs:
  plan:
    docker:
      - image: hashicorp/terraform:0.11.7
    steps:
      - checkout
      - run: mkdir -p workspace
      - run: bin/check_master.sh
      - run:
          name: lint
          command: bin/lint.sh
      - add_ssh_keys:
          fingerprints:
            - "01:23:45:67:89:10:11:12:13:14:15:16:17:18:19:20"
      - run: bin/plan.sh
      - persist_to_workspace:
          root: workspace
          paths:
            - .terraform.*.tar.gz
            - terraform.*.plan
            - changed_layers

  apply:
    docker:
      - image: hashicorp/terraform:0.11.7
    steps:
      - checkout
      - run: bin/check_master.sh
      - add_ssh_keys:
          fingerprints:
            - "01:23:45:67:89:10:11:12:13:14:15:16:17:18:19:20"
      - attach_workspace:
          at: workspace
      - run: bin/apply.sh


workflows:
  version: 2
  build_and_test:
    jobs:
      - plan
      - hold:
          type: approval
          requires:
           - plan
          filters:
            branches:
             ignore: master
      - apply:
          requires:
            - hold
          filters:
            branches:
             ignore: master
