version: 2
jobs:
  plan:
    docker:
      - image: hashicorp/terraform:0.11.4
    steps:
      - checkout
      - run:
          name: lint
          command: ./scripts/lint.sh
      - add_ssh_keys:
          fingerprints:
            - "01:23:45:67:89:10:11:12:13:14:15:16:17:18:19:20"
      - run: mkdir -p workspace
      - run: terraform init -input=false -no-color
      - run: terraform plan -no-color -input=false -out=workspace/terraform.plan
      - run: tar -czf workspace/.terraform.tar.gz .terraform
      - persist_to_workspace:
          root: workspace
          paths:
            - .terraform.tar.gz
            - terraform.plan

  apply:
    docker:
      - image: hashicorp/terraform:0.11.4
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "01:23:45:67:89:10:11:12:13:14:15:16:17:18:19:20"
      - attach_workspace:
          at: workspace
      - run: tar xzf workspace/.terraform.tar.gz
      - run: terraform apply -input=false -no-color workspace/terraform.plan


workflows:
  version: 2
  build_and_test:
    jobs:
      - plan
      - hold:
          type: approval
          requires:
           - plan
          filters:
            branches:
             ignore: master
      - apply:
          requires:
            - hold
          filters:
            branches:
             ignore: master
