version: 2
jobs:
  plan:
    docker:
      - image: hashicorp/terraform:0.11.7
    steps:
      - checkout
      - run: bin/lint.sh
      - add_ssh_keys:
          fingerprints:
            - "01:23:45:67:89:10:11:12:13:14:15:16:17:18:19:20"
      - run:
          name: bin/plan.sh
          command: bin/plan.sh
          no_output_timeout: 20m # don't break if it takes a while to refresh/plan
      - persist_to_workspace:
          root: workspace
          paths:
            - .terraform.*.tar.gz
            - terraform.*.plan
            - changed_layers
            - full_plan_output.log

  apply:
    docker:
      - image: hashicorp/terraform:0.11.7
    steps:
      - checkout
      - attach_workspace:
          at: workspace
      - add_ssh_keys:
          fingerprints:
            - "01:23:45:67:89:10:11:12:13:14:15:16:17:18:19:20"
      - run: bin/apply.sh


workflows:
  version: 2
  build_and_test:
    jobs:
      - plan
      - apply:
          requires:
            - plan
          filters:
            branches:
             only: master
