version: 2
jobs:
  test:
    docker:
      - image: hashicorp/terraform:0.11.7
    steps:
      - checkout
      - run: mv modules layers
      - run:
          name: lint
          command: bin/lint.sh
      - run: mkdir -p workspace
      - run:
          name: validate
          command: bin/validate.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
