version: 2
jobs:
  test:
    docker:
      - image: hashicorp/terraform:0.11.5
    steps:
      - checkout
      - run:
          name: lint
          command: ./scripts/lint.sh
      - run:
          name: validate
          command: ./scripts/validate.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
