version: 2
jobs:
  lint:
    docker:
      - image: hashicorp/terraform:0.11.4
    steps:
      - checkout
      - run:
          name: lint
          command: |
            lint_failed="no"
            for file in $(find . -name "*tf")
            do
              lines=$(terraform fmt -write=false -list=true ${file} | wc -l | sed 's/[^0-9]//g')
              if [ ${lines} != "0" ]
              then
                echo "Please run terraform fmt ${file}"
                lint_failed="yes"
              fi
            done
            if [ ${lint_failed} != "no" ]; then exit 1; fi

  validate:
    docker:
      - image: hashicorp/terraform:0.11.4
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "26:78:22:49:b0:74:1e:a7:cf:d9:7a:6c:1c:d4:42:55"
      - run:
          name: terraform init
          command: terraform init -input=false -backend=false -no-color
      - run:
          name: terraform validate
          command: |
            validate_failed="no"
            TF_DIRS=$(find $(pwd) -type f -iname "*.tf*" -exec dirname '{}' \; | grep -v ".terraform" | sort | uniq | xargs echo)
            for DIR in $TF_DIRS
            do
              echo Processing $DIR
              lines=$(terraform validate -input=false -check-variables=false -no-color $DIR | wc -l | sed 's/[^0-9]//g')
              if [ ${lines} != "0" ]
              then
                echo "Please run terraform validate ${file}"
                validate_failed="yes"
              fi
            done
            if [ ${validate_failed} != "no" ]; then exit 1; fi

  plan:
    docker:
      - image: hashicorp/terraform:0.11.4
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "26:78:22:49:b0:74:1e:a7:cf:d9:7a:6c:1c:d4:42:55"
      - run: mkdir -p workspace
      - run: terraform init -input=false -no-color
      - run: terraform plan -no-color -input=false -out=workspace/terraform.plan
      - persist_to_workspace:
          root: workspace
          paths:
            - terraform.plan

  apply:
    docker:
      - image: hashicorp/terraform:0.11.4
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "26:78:22:49:b0:74:1e:a7:cf:d9:7a:6c:1c:d4:42:55"
      - attach_workspace:
          at: workspace
      - run: terraform init -input=false -no-color
      - run: terraform apply -input=false -no-color workspace/terraform.plan

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - validate
      - plan:
          requires:
            - validate
      - hold:
          type: approval
          requires:
           - plan
          filters:
            branches:
             ignore: master
      - apply:
          requires:
            - hold
          filters:
            branches:
             ignore: master
